### ISSUE TITLE
Rollup: 'quill' is apparently not exported? 

### ISSUE THREAD

**Issue by sho13** [kevmodrome/svelte-quill#2]
I'm importing quill as followed in your README
`    import { quill } from "svelte-quill";`
and I get this error from my build
`Error: 'quill' is not exported by node_modules/svelte-quill/dist/index.umd.js`

Any insight?

**Comment by kevmodrome** [comment]
Not sure what might be going on, looking at the REPL it's working fine: https://svelte.dev/repl/0cc84ebc0b114dd7ab5b20b87bbee486?version=3.19.1

**Comment by kevmodrome** [comment]
Closing, please make a comment if you still have this problem.
