### ISSUE TITLE
Sapper gives "ReferenceError: document is not defined"

### ISSUE THREAD

**Issue by schindld** [kevmodrome/svelte-quill#3]
How did you get this working without wrapping your js in onMount?

**Comment by schindld** [comment]
I had to follow this to get it working with onMount: https://www.youtube.com/watch?v=EzT1IjPeieE

**Comment by ggaabe** [comment]
How do you retrieve the quill instance to make other native API calls such as insertText?

**Comment by mylastore** [comment]
@schindld did you install it with the -D flag? `npm i -D svelte-quill`

**Comment by schindld** [comment]
@mylastore Yes, I added it to devDependencies.
